language: swift
osx_image: xcode10.3
podfile: Podfile

install:
  - bundle install

script:
  - 

stages: 
  - test
  - preProduction
  - production

jobs: 
  include:
  	if: branch = develop
    - stage: preProduction
      name: "PreProduction"
	  script: xcodebuild -project Karate.xcodeproj -scheme Karate CODE_SIGNING_REQUIRED=NO
    if: branch: master
	- stage: production
	  name: "Production"
	  script: xcodebuild -project Karate.xcodeproj -scheme Karate


