language: swift
osx_image: xcode10.3
xcode_project: Karate.xcodeproj
xcode_scheme: Karate
podfile: Podfile

install:
  	- bundle install

script:
  	- CODE_SIGNING_REQUIRED=NO

stages: 
	- test
	- name: production
	if: brabch = develop

jobs: 
	include:
		- stage: production
		name: "Production"
