language: swift
osx_image: xcode10.3
xcode_project: Karate.xcodeproj
xcode_scheme: Karate
podfile: Podfile

install:
  - bundle install

script:
  - -workspace Karate.xcworkspace -scheme Karate CODE_SIGNING_REQUIRED=NO
