os: osx
language: swift
osx_image: xcode10.3

install:
  - bundle install
  - bundle exec pod install

stages: 
  - development
  - production

jobs: 
  include:
    - stage: development
      script: xcodebuild clean build -workspace Karate.xcworkspace -scheme "Karate" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=12.4,name=iPhone 8" CODE_SIGNING_REQUIRED=NO


