os: osx
language: swift
osx_image: xcode10.3
podfile: Podfile

install:
  - bundle install

before_script:
  - bundle exec pod install

stages: 
  - development
  - production

jobs: 
  - include:
    - stage: development
      provider: script
      script: xcodebuild clean build -workspace Karate.xcworkspace -scheme "Karate" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=12.4,name=iPhone 8" CODE_SIGNING_REQUIRED=NO
    - stage: production
      provider: script
      script: bash .travis/production.sh

