os: osx
language: swift
osx_image: xcode10.3
podfile: Podfile

install:
  - bundle install

jobs: 
  - include:
    - stage: stages
      script: .travis/stages.sh
      branches:
        only:
 		- develop

stages: 
  - stages