os: osx
language: swift
osx_image: xcode10.3
podfile: Podfile

install:
  - bundle install

script: 
  - xcodebuild clean build -workspace Karate.xcworkspace -scheme "Karate" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=12.4,name=iPhone 8" CODE_SIGNING_REQUIRED=NO



