language: swift
osx_image: xcode10.3
podfile: Podfile

install:
  - bundle install

script:
  - 

stages: 
  - test
  - preProduction
  - production

jobs: 
  include:
    - stage: preProduction
      name: "PreProduction"
	  script: xcodebuild -project Karate.xcodeproj -scheme Karate CODE_SIGNING_REQUIRED=NO
	  branches: 
	    only: 
	    - develop
	- stage: production
	  name: "Production"
	  script: xcodebuild -project Karate.xcodeproj -scheme Karate
	  branches: 
	    only:
	    - master


