language: swift
osx_image: xcode10.3
xcode_project: Karate.xcodeproj
xcode_scheme: Karate
podfile: Podfile

install:
  - bundle install

script:
  - CODE_SIGNING_REQUIRED=NO

stages: 
  - test
  - preProduction
  - production

jobs: 
  include:
    - stage: preProduction
	  name: "preProduction"
	  branches: 
	    only: 
	    - develop
