os: osx
language: swift
osx_image: xcode10.3
podfile: Podfile

install:
  - bundle install

stages: 
  - development
  - production

jobs: 
  - include:
    - stage: development
      script: .travis/development.sh
    - stage: production
      script: .travis/production.sh

