language: swift
osx_image: xcode10.3
podfile: Podfile

install:
  - bundle install

jobs: 
	include:
		- stage: preProduction
      	script: 
        	- xcodebuild -project Karate.xcodeproj -scheme Karate CODE_SIGNING_REQUIRED=NO
		- stage: production
	  	script: 
	    	- xcodebuild -project Karate.xcodeproj -scheme Karate
	  	branches:
	    	only:
	    	- master


