os: osx
language: swift
osx_image: xcode10.3
podfile: Podfile

install:
  - bundle install

script:
  - bundle exec pod install

stages: 
  - development
  - production

jobs: 
  - include:
    - stage: development
      provider: script
      script: bash .travis/development.sh
    - stage: production
      provider: script
      script: bash .travis/production.sh

