
default_platform(:ios)
setup_travis

platform :ios do
  desc "Description of what the lane does"
  lane :production do
    create_keychain(
  	 unlock: true,
  	 name: "login",
  	 password: "328445"  	
  	)
  end

  desc "Build app"
  lane :build do 
  	create_keychain(
  	 unlock: true,
  	 name: "login",
  	 password: "328445"  	
  	)
    match(
     type: "development",
     git_url: "https://github.com/fatihkaganemre/Certificates.git"
    )
  	build_app(
  	 scheme: "Karate",
     workspace: "Karate.xcworkspace",
     include_bitcode: true,
     clean: true
  	)
  end
end
